const ActionType = {
	CHANGE_POPUP: 'CHANGE_POPUP',
	CHANGE_ISLOGIN: 'CHANGE_ISLOGIN',
	CHANGE_USER: 'CHANGE_USER',
	CHANGE_ISLOADING: 'CHANGE_ISLOADING',
	SET_NOTES: 'SET_NOTES',
}

export default ActionType
